### PR TITLE
Add branding for nengo-spa

### PR DESCRIPTION
**Pull request by Seanny123**
Now that `nengo-spa` has some documentation, it's going to need a logo. This PR covers this.

### CODE REVIEW

**Comment by jgosmann** [comment]
Added all the logos.

**Comment by Seanny123** [comment]
I don't understand the TravisCI error. Any ideas?

```
/home/travis/build/nengo/design/nengo_spa/README.rst:42:duplicate label favicon, other instance in /home/travis/build/nengo/design/nengo_dl/README.rst
```

**Comment by Seanny123** [comment]
NVM. Figured it out.

**Comment by jgosmann** [comment]
- [x] I forgot to convert the SPA part into an outline (which may display it incorrectly on systems without that font).
- [x] The font used should be referenced in the readme.

**Comment by tbekolay** [comment]
Is this ready to go now or are some things still todo?

**Comment by Seanny123** [comment]
It's ready now.

**Review by tbekolay — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
