### PR TITLE
Add nengo-ocl logo

### PR DESCRIPTION
**Pull request by bmorcos**
Created logo for Nengo OCL.

Colour chosen via quick poll, it's relatively easy to change if we decide to do that during the review process.

### CODE REVIEW

**Comment by tbekolay** [comment]
Just occurred to me... one thing that I think we've never fully talked about is whether the name of the project is "Nengo OCL" or "Nengo OpenCL". In the past, I thought that it was "Nengo OpenCL" even though we often say "Nengo OCL" out loud (which I took to be an abbreviation). I would normally look to the documentation for guidance here, but there isn't any documentation, so we should probably make that decision before finalizing the logo.

**Comment by bmorcos** [comment]
I don't have a strong opinion either way

**Comment by drasmuss** [comment]
I think "OCL" is not a generally used shorthand for "OpenCL", it's just something we started doing. E.g., googling "OCL" doesn't turn up anything related to OpenCL. So we should probably go with OpenCL.

Edit: Actually, "OCL" is used in a few other projects listed here https://en.wikipedia.org/wiki/OpenCL, so it's not unheard of anyway.

**Comment by bmorcos** [comment]
Here's what that looks like:

full-light

full-dark

**Comment by hunse** [comment]
Changed back to OCL, since that's what we're going with. Otherwise, this LGTM!

**Review by hunse — APPROVED** [review]

**Comment by bmorcos** [comment]
The logo looks cutoff on the right hand side and the top, might need to change the size of the "page" or whatever it's called when saving the image.

**Comment by tbekolay** [comment]
I also like the OpenCL green over this yellow :shrug:

**Comment by hunse** [comment]
NengoBraindrop is green, which is why we went with this I think (there was a poll back in March or whenever). I've also changed the text to paths in the logo, which should fix any cutoff issues.

**Comment by bmorcos** [comment]
Logos look good!

As for colour, I personally don't have a strong opinion, but for what it's worth, it's a pretty different green and we _do_ have two blue themes which are pretty similar (Loihi and SpiNNaker). Not that it's a good precedent to follow though :joy:

**Comment by tbekolay** [comment]
Yeah we're going to run out of colors quickly if our goal is to make them as different as possible, it's fine for them to be similar (ideally not exactly the same)

**Comment by hunse** [comment]
Ok, I've changed to green (borrowed from the OpenCL logo). 

image

image

It's different enough from the NengoBraindrop logo.

**Comment by bmorcos** [comment]
Fresh 2 Death! LGTM :cake:

**Pull request merged**
